[[library]]
name = "libavcodec"

[[library]]
name = "libavdevice"

[[library]]
name = "libavfilter"

[[library]]
name = "libavformat"

[[library]]
name = "libavutil"

[[library]]
name = "libpostproc"
file = "libavutil.so" # Removed in 8.0 and no one is using this ATM. Use a dummy one before archlinux package the new libpostproc library

[[library]]
name = "libswresample"

[[library]]
name = "libswscale"

[[binary]]
name = "ffmpeg"

[[binary]]
name = "ffprobe"
